# Class 2, in-class work
Date : Jan 25, 2018

In [1]:
my_string = "hello world"

In [2]:
print(my_string)

hello world


In [5]:
my_string [2]

'l'

## Playing with slices
Syntax of a slice my_string[start:end] where end is not inclusive

In [8]:
my_string [0:5]

'hello'

Here is a function to know how to know the length og a string: len()

In [11]:
len(my_string)

11

To access the last element, use index -1

In [12]:
my_string[-1]

'd'

What's a good way to get all of the characters of my_string, expect the last one?

In [13]:
my_string[0:-1]

'hello worl'

You can also do slices as: 'start:end:step...and a -1 step goes backwords!

In [15]:
my_string[0:10]

'hello worl'

In [16]:
my_string[0:len(my_string)]

'hello world'

In [18]:
my_string[::-1]

'dlrow olleh'

In [22]:
my_string = "engineer"

In [23]:
my_string[0:8]

'engineer'

In [24]:
my_string = "banana"

In [25]:
my_string[1]

'a'

In [26]:
my_string[-1]

'a'

In [27]:
my_string[1:4]

'ana'

In [28]:
eng_string = 'engineer'

In [30]:
print(eng_string)

engineer


In [31]:
eng_string[2:5]

'gin'

## Slicing on Numpy array
Array are the wssential data structure in numerical computing! They are available to you via the numpy library. Load the library like this:

In [32]:
import numpy

In [33]:
x = numpy. array([2, 4, 6, 8])

In [34]:
x[0]

2

In [35]:
x[1:3]

array([4, 6])

In [49]:
x = numpy.linspace(0, 100, 26, dtype=int)

In [50]:
print(x)

[  0   4   8  12  16  20  24  28  32  36  40  44  48  52  56  60  64  68
  72  76  80  84  88  92  96 100]


In [41]:
x[3:12]

array([ 12.,  16.,  20.,  24.,  28.,  32.,  36.,  40.,  44.])

In [56]:
y = numpy.arange(0,100.0,4)

In [57]:
print(y)

[  0.   4.   8.  12.  16.  20.  24.  28.  32.  36.  40.  44.  48.  52.  56.
  60.  64.  68.  72.  76.  80.  84.  88.  92.  96.]


In [58]:
type(x)

numpy.ndarray

In [59]:
type(y[0])

numpy.float64

In [60]:
type(x[0])

numpy.int64

Welcome 2D Arrays!

In [62]:
X = numpy.array([[1, 2], [3, 4]])
print(X)

[[1 2]
 [3 4]]


From the X array:

Grab the 2nd element in the 1st column.
Grab the 2nd element in the 2nd column.

In [64]:
X[0,1]

2

In [65]:
X[1,1]

4

In [68]:
X[0,:]

array([1, 2])

In [69]:
X[:,0]

array([1, 3])